version: '2'
services:
  db:
    container_name: team5_mysql ## 
    build: mysql/.
    image: hyeonjames/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=a1234567@
      - MYSQL_PORT=3306
  web:
    container_name: team5_tomcat ## 
    expose:
      - "8009"
    build: tomcat/.
    image: hyeonjames/tomcat
    environment:
      - OPEN_API_KEY=Ik6zomYwmtDENJcCDgLVXlDTrXcjQ7JVm3EPLIQbPeO%2F%2B6W3h39mSASeNCRESjhUNp7jXLmVx5s7%2BkBMuSX5oQ%3D%3D
      - MYSQL_NAME=team5_mysql
      - MYSQL_USER_NM=root
      - MYSQL_USER_PW=a1234567@
  httpd:
    container_name: team5_apache
    ports:
      - "80:80"
    build: httpd/.
    image: hyeonjames/apache
    environment:
      - TOMCAT_NAME=team5_tomcat
    