#!/bin/sh
### BEGIN INIT INFO
# Provides:     DustNotify
# Required-Start:   $all
# Required-Stop:
# Default-Start:    2 3 4 5
# Default-Stop
# Short-Description dust notify docker
### END INIT INFO
# start/stop dustdocker daemon
#

DUST_PATH=/home/ubuntu/Team5
NAME=dustdocker

case "$1" in
    start)
        cd $DUST_PATH
        sh startup.sh
        ;;
    stop)
        cd $DUST_PATH
        docker-compose down
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage {start|stop|restart}"
    exit 1
    ;;
esac

exit 0